"""Telegram notification sender for stock signals."""

import httpx
from app.config import settings
from app.signals.engine import SignalResult


def format_signal_message(ticker: str, signals: list[SignalResult], summary: str) -> str:
    """
    Format signals into Telegram Markdown message.

    Args:
        ticker: Stock ticker symbol
        signals: List of SignalResult objects
        summary: LLM-generated or fallback summary text

    Returns:
        Formatted Telegram Markdown message
    """
    if not signals:
        return f"No signals generated for {ticker}"

    # Get the strongest signal (for emoji and title)
    strongest = max(signals, key=lambda s: s.confidence)

    # Map signal type and level to emoji
    emoji_map = {
        ("BUY", "STRONG"): "🟢",
        ("BUY", "WEAK"): "🟢",
        ("SELL", "STRONG"): "🔴",
        ("SELL", "WEAK"): "🔴",
        ("WATCH",): "🟡",
    }

    key = (strongest.signal_type, strongest.signal_level) if strongest.signal_level != "WATCH" else ("WATCH",)
    emoji = emoji_map.get(key, "⚪")

    # Format signal level for display
    signal_level_display = "STRONG BUY" if (strongest.signal_type == "BUY" and strongest.signal_level == "STRONG") else \
                          "STRONG SELL" if (strongest.signal_type == "SELL" and strongest.signal_level == "STRONG") else \
                          strongest.signal_type

    # Build message
    lines = [
        f"{emoji} *{signal_level_display} Signal* — {ticker}",
        "",
        "📊 *技术指标共振*",
    ]

    # Add indicator details from all signals
    for signal in signals:
        if signal.signal_level != "WATCH":  # Skip WATCH signals in the main confluence section
            target_str = f" | 目标价: ${signal.target_price:.2f}" if signal.target_price else ""
            lines.append(f"• {signal.indicator}{target_str} | 置信度: {signal.confidence}%")

    lines.extend([
        "",
        "💡 *LLM 分析*",
        summary,
        "",
        "⚡ Generated by Stock Signal Monitor",
    ])

    return "\n".join(lines)


async def send_telegram(message: str) -> bool:
    """
    Send message via Telegram Bot API.

    Args:
        message: Telegram Markdown formatted message

    Returns:
        True if successful, False otherwise
    """
    if not settings.telegram_bot_token or not settings.telegram_chat_id:
        return False

    url = f"https://api.telegram.org/bot{settings.telegram_bot_token}/sendMessage"
    payload = {
        "chat_id": settings.telegram_chat_id,
        "text": message,
        "parse_mode": "Markdown",
    }

    try:
        async with httpx.AsyncClient() as client:
            resp = await client.post(url, json=payload, timeout=10)
            return resp.status_code == 200
    except Exception:
        return False
