"""Telegram notification sender for stock signals."""

import httpx
from app.config import settings
from app.signals.engine import SignalResult


def _escape_md(text: str) -> str:
    """Escape Telegram Markdown v1 special characters in dynamic (LLM-generated) content.

    Unescaped _ * ` [ in user/LLM content break entity parsing and trigger
    "Can't find end of entity" errors from the Telegram Bot API.
    """
    if not text:
        return text
    for ch in ("_", "*", "`", "[", "]"):
        text = text.replace(ch, f"\\{ch}")
    return text


def format_signal_message(
    ticker: str,
    signals: list[SignalResult],
    summary: str,
    verdict: str | None = None,
    position_note: str | None = None,
) -> str:
    """Format a STRONG signal push with full entry/exit/risk details."""

    if not signals:
        return f"No signals generated for {ticker}"

    strong = [s for s in signals if isinstance(s, SignalResult) and s.signal_level == "STRONG"]
    if not strong:
        # Fall back to strongest signal when no STRONG signals present
        strongest = max(signals, key=lambda s: s.confidence)
        emoji_map = {
            ("BUY", "STRONG"): "🟢",
            ("BUY", "WEAK"): "🟢",
            ("SELL", "STRONG"): "🔴",
            ("SELL", "WEAK"): "🔴",
            ("WATCH",): "🟡",
        }
        key = (strongest.signal_type, strongest.signal_level) if strongest.signal_level != "WATCH" else ("WATCH",)
        emoji = emoji_map.get(key, "⚪")
        signal_level_display = (
            "STRONG BUY" if (strongest.signal_type == "BUY" and strongest.signal_level == "STRONG") else
            "STRONG SELL" if (strongest.signal_type == "SELL" and strongest.signal_level == "STRONG") else
            strongest.signal_type
        )
        lines = [
            f"{emoji} *{signal_level_display} Signal* — {ticker}",
            "",
            "📊 *技术指标共振*",
        ]
        for signal in signals:
            if signal.signal_level != "WATCH":
                target_str = f" | 目标价: ${signal.target_price:.2f}" if signal.target_price else ""
                lines.append(f"• {signal.indicator}{target_str} | 置信度: {signal.confidence}%")
        lines.extend(["", "💡 *LLM 分析*", _escape_md(summary), "", "⚡ Generated by Stock Signal Monitor"])
        return "\n".join(lines)

    sig = strong[0]
    direction = "🟢 做多" if sig.signal_type == "BUY" else "🔴 做空"
    lines = [
        f"*{ticker}* — {direction}  `{sig.indicator}`",
        f"置信度: {sig.confidence}%",
        "",
    ]

    if sig.entry_low is not None and sig.entry_high is not None:
        lines.append(f"📥 *进场区间:*  ${sig.entry_low:.2f} ~ ${sig.entry_high:.2f}  _（3日内有效）_")
    if sig.target_price:
        rr_str = f"  R:R {sig.rr_ratio:.1f}" if sig.rr_ratio is not None else ""
        lines.append(f"🎯 *目标价:*     ${sig.target_price:.2f}{rr_str}")
    if sig.stop_price:
        lines.append(f"🛑 *止损价:*     ${sig.stop_price:.2f}")
    if sig.partial_tp:
        lines.append(f"💰 *分批止盈:*  ${sig.partial_tp:.2f}  _（卖50%，止损移保本）_")

    lines.append("")
    if sig.volume_ratio:
        lines.append(f"📦 成交量: {sig.volume_ratio:.1f}× 均量 ✅")
    if sig.regime:
        lines.append(f"🌍 大盘: {sig.regime}")

    if summary:
        lines.extend(["", f"_{_escape_md(summary)}_"])

    if verdict:
        lines.extend(["", f"🧠 *辩论裁决:* {_escape_md(verdict)}"])

    if position_note:
        lines.extend(["", _escape_md(position_note)])

    return "\n".join(lines)


async def send_telegram(message: str) -> bool:
    """
    Send message via Telegram Bot API.

    Args:
        message: Telegram Markdown formatted message

    Returns:
        True if successful, False otherwise
    """
    if not settings.telegram_bot_token or not settings.telegram_chat_id:
        return False

    url = f"https://api.telegram.org/bot{settings.telegram_bot_token}/sendMessage"
    payload = {
        "chat_id": settings.telegram_chat_id,
        "text": message,
        "parse_mode": "Markdown",
    }

    try:
        async with httpx.AsyncClient() as client:
            resp = await client.post(url, json=payload, timeout=10)
            if resp.status_code == 200:
                return True
            # Retry without parse_mode if Telegram rejects the Markdown formatting
            if resp.status_code == 400 and "parse" in resp.text.lower():
                plain_payload = {
                    "chat_id": settings.telegram_chat_id,
                    "text": message,
                }
                resp2 = await client.post(url, json=plain_payload, timeout=10)
                return resp2.status_code == 200
            return False
    except Exception:
        return False
