"""
Stock Signal Monitor — MCP Server

Exposes stock monitoring capabilities as MCP tools for Claude/AI agents.
Transport: stdio (Claude Desktop / Claude Code compatible)

Usage:
    python -m app.mcp_server

Claude Desktop config (~/.claude/claude_desktop_config.json):
    {
      "mcpServers": {
        "stock_monitor": {
          "command": "python",
          "args": ["-m", "app.mcp_server"],
          "cwd": "/path/to/stock-signal-monitor",
          "env": { "DATABASE_URL": "...", "TELEGRAM_BOT_TOKEN": "..." }
        }
      }
    }
"""

import logging
from datetime import UTC, datetime, timedelta
from typing import Optional

from mcp.server.fastmcp import FastMCP
from pydantic import BaseModel, Field

logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger(__name__)

mcp = FastMCP("stock_monitor_mcp")


# ── Input models ─────────────────────────────────────────────────────────────

class TickerInput(BaseModel):
    ticker: str = Field(..., description="Stock ticker symbol, e.g. AAPL, NVDA, TSLA", min_length=1, max_length=10)


class SignalsInput(BaseModel):
    ticker: Optional[str] = Field(None, description="Filter by ticker symbol. Omit for all tickers.")
    level: Optional[str] = Field(None, description="Filter by signal level: STRONG, WEAK, or WATCH")
    limit: int = Field(20, description="Max number of signals to return", ge=1, le=100)


class CalendarInput(BaseModel):
    days: int = Field(14, description="Number of days ahead to look", ge=1, le=90)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _get_db():
    from app.database import SessionLocal
    return SessionLocal()


def _level_emoji(level: str) -> str:
    return {"STRONG": "🔴", "WEAK": "🟡", "WATCH": "⚪"}.get(level, "⚪")


def _dir_emoji(signal_type: str) -> str:
    return {"BUY": "🟢", "SELL": "🔴", "WATCH": "🟡"}.get(signal_type, "⚪")


# ── Tools ─────────────────────────────────────────────────────────────────────

@mcp.tool(name="stock_monitor_get_watchlist")
async def get_watchlist() -> str:
    """
    List all active stocks in the watchlist being monitored for signals.
    Returns ticker symbols and company names.
    """
    from app.models import WatchlistItem
    db = _get_db()
    try:
        items = db.query(WatchlistItem).filter(WatchlistItem.is_active == True).all()  # noqa: E712
        if not items:
            return "Watchlist is empty."
        lines = [f"📈 Watchlist ({len(items)} stocks):\n"]
        for item in items:
            name_str = f" — {item.name}" if item.name else ""
            lines.append(f"  • {item.ticker}{name_str}")
        return "\n".join(lines)
    finally:
        db.close()


@mcp.tool(name="stock_monitor_add_stock")
async def add_stock(params: TickerInput) -> str:
    """
    Add a stock ticker to the watchlist. The stock will be included in the next daily scan.
    Fetches company name from yfinance automatically.
    """
    import re
    ticker = params.ticker.upper().strip()
    if not re.fullmatch(r"[A-Z]{1,10}", ticker):
        return f"❌ Invalid ticker format: {ticker}"

    from app.database import SessionLocal
    from app.models import WatchlistItem
    db = SessionLocal()
    try:
        existing = db.query(WatchlistItem).filter(WatchlistItem.ticker == ticker).first()
        if existing and existing.is_active:
            return f"⚠️ {ticker} is already in the watchlist."
        name = ticker
        try:
            import yfinance as yf
            info = yf.Ticker(ticker).info
            name = info.get("shortName") or info.get("longName") or ticker
        except Exception:
            pass
        if existing:
            existing.is_active = True
            db.commit()
        else:
            db.add(WatchlistItem(ticker=ticker, name=name))
            db.commit()
        return f"✅ Added {ticker} ({name}) to watchlist."
    finally:
        db.close()


@mcp.tool(name="stock_monitor_remove_stock")
async def remove_stock(params: TickerInput) -> str:
    """
    Remove a stock ticker from the watchlist (soft delete — keeps signal history).
    """
    from app.models import WatchlistItem
    ticker = params.ticker.upper().strip()
    db = _get_db()
    try:
        item = db.query(WatchlistItem).filter(WatchlistItem.ticker == ticker).first()
        if not item or not item.is_active:
            return f"⚠️ {ticker} is not in the active watchlist."
        item.is_active = False
        db.commit()
        return f"🗑 Removed {ticker} from watchlist."
    finally:
        db.close()


@mcp.tool(name="stock_monitor_get_signals")
async def get_signals(params: SignalsInput) -> str:
    """
    Retrieve recent trading signals from the database.
    Signals are generated by the daily scanner (MACD, RSI, MA cross, Bollinger confluence).
    Signal levels: STRONG = 2+ indicators confluent, WEAK = single indicator, WATCH = near threshold.
    """
    from app.models import Signal
    db = _get_db()
    try:
        query = db.query(Signal).order_by(Signal.triggered_at.desc())
        if params.ticker:
            query = query.filter(Signal.ticker == params.ticker.upper())
        if params.level:
            query = query.filter(Signal.signal_level == params.level.upper())
        signals = query.limit(params.limit).all()

        if not signals:
            filters = []
            if params.ticker:
                filters.append(f"ticker={params.ticker}")
            if params.level:
                filters.append(f"level={params.level}")
            return f"No signals found{' for ' + ', '.join(filters) if filters else ''}."

        lines = [f"📊 Signals ({len(signals)} results):\n"]
        for s in signals:
            lines.append(
                f"{_level_emoji(s.signal_level)}{_dir_emoji(s.signal_type)} "
                f"*{s.ticker}* [{s.signal_level}] {s.signal_type} | "
                f"{s.indicator} | {s.confidence}% | "
                f"{s.triggered_at.strftime('%m-%d %H:%M')} UTC\n"
                f"   {s.message}"
            )
        return "\n".join(lines)
    finally:
        db.close()


@mcp.tool(name="stock_monitor_scan")
async def scan_stocks() -> str:
    """
    Trigger an immediate scan of all watchlist stocks.
    Runs all technical indicators (MACD, RSI, MA cross, Bollinger), detects confluence,
    saves results to DB, and sends Telegram notifications for STRONG signals.
    This may take 10-30 seconds depending on watchlist size.
    """
    import asyncio
    from app.scheduler import scan_all_stocks

    try:
        loop = asyncio.get_event_loop()
        await loop.run_in_executor(None, scan_all_stocks)
    except Exception as e:
        return f"❌ Scan failed: {e}"

    from app.models import Signal
    db = _get_db()
    try:
        recent = datetime.now(UTC) - timedelta(minutes=5)
        signals = (
            db.query(Signal)
            .filter(Signal.triggered_at >= recent)
            .order_by(Signal.signal_level.desc(), Signal.confidence.desc())
            .all()
        )
        if not signals:
            return "✅ Scan complete. No signals detected."

        lines = [f"✅ Scan complete — {len(signals)} signal(s) found:\n"]
        for s in signals:
            pushed_tag = " ✈️ pushed to Telegram" if s.pushed else ""
            lines.append(
                f"{_level_emoji(s.signal_level)}{_dir_emoji(s.signal_type)} "
                f"{s.ticker} [{s.signal_level}] {s.signal_type} | "
                f"{s.indicator} | {s.confidence}%{pushed_tag}\n"
                f"   {s.message}"
            )
        strong = sum(1 for s in signals if s.signal_level == "STRONG")
        lines.append(f"\n{strong} STRONG signal(s) pushed to Telegram." if strong else "\nNo STRONG signals — Telegram not notified.")
        return "\n".join(lines)
    finally:
        db.close()


@mcp.tool(name="stock_monitor_analyze")
async def analyze_stock(params: TickerInput) -> str:
    """
    Full stock analysis for a given ticker.
    Includes: current price, pre/post-market price, support/resistance levels,
    action recommendation (buy/sell/hold with price ranges), RSI, analyst consensus,
    short interest, beta, and upcoming earnings/macro events.
    """
    import asyncio
    from app.bot.analysis import get_stock_analysis

    ticker = params.ticker.upper().strip()
    try:
        loop = asyncio.get_event_loop()
        result = await loop.run_in_executor(None, get_stock_analysis, ticker)
        return result
    except Exception as e:
        return f"❌ Analysis failed for {ticker}: {e}"


@mcp.tool(name="stock_monitor_get_calendar")
async def get_calendar(params: CalendarInput) -> str:
    """
    Get upcoming US economic events (FOMC, CPI, NFP, PCE, GDP) and watchlist earnings.
    Includes market consensus forecast and prior period values when available.
    """
    from app.bot.calendar import get_upcoming_events_from_db
    return get_upcoming_events_from_db(days=params.days)


@mcp.tool(name="stock_monitor_refresh_calendar")
async def refresh_calendar() -> str:
    """
    Force-refresh the economic calendar from Finnhub (earnings + macro forecasts/prior values).
    Run this to get the latest analyst consensus estimates before a major data release.
    """
    from app.bot.calendar import refresh_calendar as _refresh
    try:
        result = _refresh()
        return (
            f"✅ Calendar refreshed:\n"
            f"  • {result.get('official', 0)} official macro events synced\n"
            f"  • {result.get('macro_enriched', 0)} events enriched with forecast/prior\n"
            f"  • {result.get('earnings', 0)} earnings events updated"
        )
    except Exception as e:
        return f"❌ Refresh failed: {e}"


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    mcp.run(transport="stdio")
